version: "3.9"

services:
  api_gestor:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: api_gestor
    ports:
      - "5000:5000"

  nodo1:
    build:
      context: ./nodo
      dockerfile: Dockerfile.nodo
    container_name: nodo1
    ports:
      - "5001:5001"
    depends_on:
      - api_gestor

  nodo2:
    build:
      context: ./nodo
      dockerfile: Dockerfile.nodo
    container_name: nodo2
    ports:
      - "5002:5001"  
    depends_on:
      - api_gestor
